### PR TITLE
Xml parser

### PR DESCRIPTION
**Pull request by KernelOverseer**
Added xml parser and documentation for it,
tested it and fixed some makefile issues.

### CODE REVIEW

**Review by yezz123 — APPROVED** [review]

**Review by fdrissi — COMMENTED** [review]
It's been a while since the last time I've checked a C code, great job on that @KernelOverseer 👍 .
 I have one suggestion since you've already named the directory ```xml_parser``` IMO I think you don't need to include the word ```parser``` in each filename.

**Comment by KernelOverseer** [comment]
@fdrissi i agree with you, i didn't pay attention to that, I'll update it, Thanks!

**Comment by fdrissi** [comment]
LGTM (structure-wise).
Didn't check the code really well, need to be reviewed by another experienced C dev.

**Comment by KernelOverseer** [comment]
@fdrissi thanks, I'll assign someone else to double-check.

**Review by drslax — APPROVED** [review]

**Pull request merged**
